# Generated by Django 5.0.1 on 2025-12-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("beds", models.IntegerField()),
                ("email", models.EmailField(max_length=255)),
                ("search", models.IntegerField()),
                ("delete_key", models.IntegerField()),
            ],
            options={
                "db_table": "alerts",
                "managed": True,
            },
        ),
    ]
