# Generated by Django 5.0.1 on 2025-12-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Directory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "contact_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("date_modified", models.DateField(auto_now=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Landlord", "Landlord"),
                            ("Manager", "Manager"),
                            ("Complex", "Complex"),
                            ("Business", "Business"),
                            ("Team Syracuse", "Team Syracuse"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Directories",
                "db_table": "directory",
                "managed": True,
            },
        ),
    ]
