# Generated by Django 5.0.1 on 2025-12-09 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingListing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_added", models.DateField(auto_now_add=True)),
                ("months", models.IntegerField()),
                ("featured", models.CharField(max_length=255)),
                ("spotlight", models.CharField(max_length=255)),
                ("userId", models.IntegerField()),
            ],
            options={
                "db_table": "pending_listings",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("zip", models.IntegerField(blank=True, null=True)),
                ("unit", models.IntegerField(default=0)),
                ("beds", models.IntegerField(blank=True, null=True)),
                ("baths", models.CharField(blank=True, max_length=3, null=True)),
                ("rent", models.IntegerField(blank=True, null=True)),
                ("utilities", models.CharField(blank=True, max_length=7, null=True)),
                ("pets", models.CharField(blank=True, max_length=5, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("date_avail", models.DateField(blank=True, null=True)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_expires", models.DateField()),
                ("contact_name", models.CharField(max_length=255)),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "contact_email",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("visible", models.BooleanField(default=True)),
                ("featured", models.IntegerField(default=0)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "perfect_for",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "building_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("furnished", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "lease_length",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("tenant_lease_end", models.DateField(blank=True, null=True)),
                ("fireplace", models.CharField(blank=True, max_length=255, null=True)),
                ("dishwasher", models.CharField(blank=True, max_length=255, null=True)),
                ("laundry", models.CharField(blank=True, max_length=255, null=True)),
                ("porch", models.CharField(blank=True, max_length=255, null=True)),
                ("parking", models.CharField(blank=True, max_length=255, null=True)),
                ("smoking", models.CharField(blank=True, max_length=255, null=True)),
                ("is_season", models.CharField(blank=True, max_length=255, null=True)),
                ("total_beds", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "house_kitchen",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "house_chores",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "house_sleep",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "house_clean",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "house_drink",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("we_are", models.CharField(blank=True, max_length=255, null=True)),
                ("we_prefer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "beds_needed",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("i_am", models.CharField(blank=True, max_length=255, null=True)),
                ("max_rent", models.SmallIntegerField(blank=True, null=True)),
                ("my_gender", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "prefer_gender",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spotlightListing",
                    models.DateField(blank=True, default="2010-01-01", null=True),
                ),
                ("typeCode", models.PositiveSmallIntegerField(default=1)),
                ("latLng", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "physicalAddress",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("textOk", models.BooleanField(blank=True, null=True)),
                ("rent_type", models.CharField(default="perBed", max_length=255)),
                ("auc_is_auction", models.BooleanField(default=False)),
                ("auc_prev_rent", models.IntegerField(blank=True, null=True)),
                ("auc_buy_it_now_rent", models.IntegerField(blank=True, null=True)),
                ("auc_min_bid", models.IntegerField(blank=True, null=True)),
                ("auc_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "cover_photo_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "listings",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                ("photo_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("is_main", models.BooleanField(default=True)),
                (
                    "listing",
                    models.ForeignKey(
                        db_column="listing_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "db_table": "photos",
                "managed": True,
            },
        ),
    ]
