# Generated by Django 5.0.1 on 2025-12-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="auc_buy_it_now_rent",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="auc_end_date",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="auc_is_auction",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="auc_min_bid",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="auc_prev_rent",
        ),
    ]
