# Generated by Django 5.0.1 on 2025-12-09 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_remove_listing_auc_buy_it_now_rent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "lookup_building_types",
                "ordering": ["name"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ListingType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "lookup_listing_types",
                "ordering": ["code"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("city", models.CharField(default="Syracuse", max_length=100)),
                ("state", models.CharField(default="NY", max_length=2)),
                ("zip_prefix", models.CharField(blank=True, max_length=5, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "lookup_locations",
                "ordering": ["name"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="listing",
            name="building_type_ref",
            field=models.ForeignKey(
                blank=True,
                db_column="building_type_ref_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="listings.buildingtype",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="listing_type",
            field=models.ForeignKey(
                blank=True,
                db_column="listing_type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="listings.listingtype",
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="location_ref",
            field=models.ForeignKey(
                blank=True,
                db_column="location_ref_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="listings.location",
            ),
        ),
    ]
