# Generated by Django 5.0.1 on 2025-12-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_buildingtype_listingtype_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default=None,
                max_length=10,
                null=True,
            ),
        ),
    ]
