# Generated by Django 5.0.1 on 2025-12-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
