# Generated by Django 5.2.9 on 2025-12-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0005_listing_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="utilities",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
