# Generated by Django 5.2.9 on 2025-12-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_alter_listing_utilities"),
    ]

    operations = [
        # Rename title to listing_title
        migrations.RenameField(
            model_name="listing",
            old_name="title",
            new_name="listing_title",
        ),
        # Remove status field
        migrations.RemoveField(
            model_name="listing",
            name="status",
        ),
    ]
