# Generated by Django 5.2.9 on 2025-12-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_rename_title_remove_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="stripe_payment_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
