# Generated by Django 5.2.9 on 2025-12-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_listing_is_public_listing_stripe_payment_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="admin_feedback",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="approval_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AddField(
            model_name="listing",
            name="stripe_payment_method_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
