# Generated by Django 5.2.9 on 2025-12-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_listing_admin_feedback_listing_approval_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utility",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "lookup_utilities",
                "ordering": ["name"],
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="listing",
            name="approval_status",
            field=models.CharField(default="draft", max_length=20),
        ),
        migrations.AddField(
            model_name="listing",
            name="utilities_m2m",
            field=models.ManyToManyField(
                blank=True,
                db_table="listings_listing_utilities",
                related_name="listings",
                to="listings.utility",
            ),
        ),
    ]
