# Generated by Django 5.2.9 on 2025-12-24 03:33

from django.db import migrations


def migrate_utilities(apps, schema_editor):
    Utility = apps.get_model('listings', 'Utility')
    Listing = apps.get_model('listings', 'Listing')

    # Create default utilities - removed Trash as requested
    utils_map = {}
    utility_names = ['Gas', 'Electric', 'Water', 'Heat', 'Internet', 'Contact Manager']
    
    for name in utility_names:
        utils_map[name] = Utility.objects.create(name=name)

    # Helper to get utility objects
    def get_utils(names):
        return [utils_map[name] for name in names if name in utils_map]

    for listing in Listing.objects.all():
        old_val = str(listing.utilities).strip() if listing.utilities else ''
        
        # '0', 'Included', 'Heat, Water, Electric, Wifi' -> [Gas, Electric, Water, Heat, Internet]
        if old_val == '0' or old_val.lower() == 'included' or 'heat, water' in old_val.lower():
            listing.utilities_m2m.add(*get_utils(['Gas', 'Electric', 'Water', 'Heat', 'Internet']))
        
        # '2' -> [Gas]
        elif old_val == '2':
            listing.utilities_m2m.add(*get_utils(['Gas']))
            
        # '3' -> [Electric]
        elif old_val == '3':
            listing.utilities_m2m.add(*get_utils(['Electric']))
            
        # '4' -> [Gas, Electric]
        elif old_val == '4':
            listing.utilities_m2m.add(*get_utils(['Gas', 'Electric']))
            
        # '5' -> [Contact Manager]
        elif old_val == '5':
            listing.utilities_m2m.add(*get_utils(['Contact Manager']))

def reverse_migrate(apps, schema_editor):
    Utility = apps.get_model('listings', 'Utility')
    # We don't want to delete all utilities if we reverse, theoretically, but for this migration it makes sense to clean up what we created.
    # However, if other data was added later, this would be destructive. 
    # For now, let's just pass or delete mainly the ones we created if we wanted to be safe, but deleting all is standard for "reversing the creation of the table content".
    Utility.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0010_utility_alter_listing_approval_status_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_utilities, reverse_migrate),
    ]
