# Generated by Django 5.2.9 on 2025-12-26 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0011_migrate_utilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPostRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.TextField()),
                ("platforms", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("posted", "Posted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_feedback", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_post_requests",
                        to="listings.listing",
                    ),
                ),
            ],
            options={
                "db_table": "social_post_requests",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
    ]
