# Generated by Django 5.2.9 on 2025-12-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0012_socialpostrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="social_media_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="social_media_post_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="social_media_posted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="social_media_posting",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="SocialPostRequest",
        ),
    ]
