# Generated by Django 5.0.1 on 2025-12-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("url", models.CharField(max_length=255)),
                ("expires", models.DateField()),
                ("logo", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "ads",
                "managed": True,
            },
        ),
    ]
