# Generated by Django 5.0.1 on 2025-12-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_name",
                    models.CharField(blank=True, max_length=24, null=True, unique=True),
                ),
                ("user_email", models.EmailField(max_length=255, unique=True)),
                ("user_pass", models.CharField(max_length=60)),
                ("user_salt", models.CharField(max_length=32)),
                ("user_last_login", models.DateTimeField(blank=True, null=True)),
                ("user_login_time", models.DateTimeField(blank=True, null=True)),
                (
                    "user_session_id",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("user_date", models.DateTimeField(auto_now_add=True)),
                ("user_modified", models.DateTimeField(auto_now=True, null=True)),
                (
                    "user_agent_string",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("user_level", models.PositiveSmallIntegerField()),
                (
                    "user_banned",
                    models.CharField(
                        choices=[("0", "Not Banned"), ("1", "Banned")],
                        default="0",
                        max_length=1,
                    ),
                ),
                (
                    "passwd_recovery_code",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                ("passwd_recovery_date", models.DateTimeField(blank=True, null=True)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=255)),
                ("last_ip", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": True,
            },
        ),
    ]
