# Generated by Django 5.0.1 on 2025-12-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_type",
            field=models.CharField(
                choices=[("md5", "MD5 (Legacy)"), ("bcrypt", "Bcrypt")],
                default="bcrypt",
                max_length=10,
            ),
        ),
    ]
