# Generated by Django 5.2.9 on 2025-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facebook_page_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="facebook_token",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="has_social_subscription",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_business_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_token",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
