# Generated by Django 5.2.9 on 2026-01-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_facebook_page_id_user_facebook_token_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="facebook_page_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="facebook_token",
        ),
        migrations.RemoveField(
            model_name="user",
            name="has_social_subscription",
        ),
        migrations.RemoveField(
            model_name="user",
            name="instagram_business_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="instagram_token",
        ),
    ]
